version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces/${containerWorkspaceFolder}
    command: sh -c "php -S 0.0.0.0:8080 -t ."
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: hrms_system
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db_data: